matrix:
  include:
    - language: node_js
      node_js:
        - "8.9.4"
      before_install:
        - cd admin.api
        - chmod 0777 ./node_modules/.bin/mocha
      script: 
        - npm test
