matrix:
  include:
    - language: node_js
      node_js:
        - "8.9.4"
      services:
        - mongodb
      before_install:
        - cd admin.api
        - rm -r node_modules
      before_script:
        - cd ..
        - mongod --dbpath /admin.db
      script: 
        - npm test
