matrix:
  include:
    - language: node_js
      node_js:
        - "8.9.4"
      services:
        - mongodb
      before_install:
        - sudo service mongod stop
        - mongod --dbpath admin.db
        - cd admin.api
        - rm -r node_modules
      script: 
        - npm test
